import LegalLayout from "@/components/LegalLayout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - Bevy",
  description: "Privacy Policy for the Bevy mobile application.",
};

export default function PrivacyPolicy() {
  return (
    <LegalLayout title="Privacy Policy">
      <p><strong>Effective date: 04/04/2026</strong></p>

      <h2>1. Introduction</h2>
      <p>Welcome to Bevy, an AI-powered truth or dare mobile application operated by Anant Jain (&ldquo;us,&rdquo; &ldquo;we,&rdquo; or &ldquo;our&rdquo;). This Privacy Policy governs your use of Bevy (the &ldquo;Service&rdquo;) and explains how we collect, safeguard, and disclose information resulting from your use of our Service.</p>
      <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used herein have the same meanings as in our Terms of Service.</p>
      <p>Our Terms of Service (&ldquo;Terms&rdquo;) govern all use of our Service and, together with this Privacy Policy and our Legal Disclaimer, constitute your agreement with us (&ldquo;Agreement&rdquo;).</p>

      <h2>2. Data Controller</h2>
      <p>For the purposes of the UK General Data Protection Regulation (UK GDPR), the EU General Data Protection Regulation (EU GDPR), and other applicable data protection laws, the data controller is:</p>
      <p>Anant Jain<br />Email: bevytheapp@gmail.com<br />Location: London, United Kingdom</p>

      <h2>3. Definitions</h2>
      <p><strong>SERVICE:</strong> The Bevy mobile application operated by Anant Jain.</p>
      <p><strong>PERSONAL DATA:</strong> Any information relating to an identified or identifiable natural person.</p>
      <p><strong>USAGE DATA:</strong> Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</p>
      <p><strong>AI DATA:</strong> Data processed by or generated through our artificial intelligence systems, including prompts, responses, and interaction patterns.</p>
      <p><strong>COOKIES:</strong> Small files stored on your device.</p>
      <p><strong>DATA CONTROLLER:</strong> The natural or legal person who determines the purposes and means of processing personal data. For this Privacy Policy, Anant Jain is the Data Controller.</p>
      <p><strong>DATA PROCESSORS (OR SERVICE PROVIDERS):</strong> Any natural or legal person who processes data on behalf of the Data Controller.</p>
      <p><strong>DATA SUBJECT:</strong> Any living individual who is the subject of Personal Data.</p>
      <p><strong>USER:</strong> The individual using our Service. The User corresponds to the Data Subject.</p>

      <h2>4. Legal Basis for Processing (UK GDPR / EU GDPR)</h2>
      <p>We process your Personal Data on one or more of the following legal bases:</p>
      <ul>
        <li><strong>Consent:</strong> You have given consent to the processing of your Personal Data for one or more specific purposes.</li>
        <li><strong>Performance of a Contract:</strong> Processing is necessary for the performance of a contract to which you are a party.</li>
        <li><strong>Legitimate Interests:</strong> Processing is necessary for our legitimate interests, except where such interests are overridden by your interests or fundamental rights and freedoms.</li>
        <li><strong>Legal Obligation:</strong> Processing is necessary for compliance with a legal obligation to which we are subject.</li>
      </ul>

      <h2>5. Information Collection and Use</h2>
      <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

      <h2>6. Types of Data Collected</h2>
      <h3>Usage Data</h3>
      <p>We automatically collect information when you access the Service via a mobile device. This may include your device&rsquo;s Internet Protocol address, device type and model, operating system and version, the features of the Service you use, the time and date of your use, the time spent on those features, unique device identifiers, crash data, and other diagnostic data.</p>
      <h3>AI Interaction Data</h3>
      <p>When you use our AI-powered features, we may collect data related to your interactions with the AI system, including: the categories and types of prompts you interact with; your selections, preferences, and settings; interaction patterns and frequency of use; and feedback you provide on AI-generated content. This data is used to improve the quality, safety, and relevance of AI-generated content. We do not use your AI interaction data to build individual profiles for advertising purposes.</p>
      <h3>Tracking and Cookies Data</h3>
      <p>We use cookies and similar tracking technologies to track the activity on our Service. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, some portions of our Service may not function properly without cookies.</p>
      <h3>Data We Do NOT Collect</h3>
      <p>We do not knowingly collect: special category data (racial or ethnic origin, political opinions, religious beliefs, trade union membership, genetic or biometric data, health data, or data concerning sex life or sexual orientation); financial or payment information (all payments are processed by Apple through the App Store); or precise geolocation data.</p>

      <h2>7. Use of Data</h2>
      <p>We use the collected data for the following purposes: to provide and maintain our Service; to notify you about changes; to allow you to participate in interactive features; to provide customer support; to gather analysis or valuable information to improve our Service; to monitor usage; to detect, prevent, and address technical issues and abuse; to fulfil any other purpose for which you provide it; to carry out our obligations and enforce our rights; to provide account and subscription notices; to provide you with news, special offers, and general information unless you have opted out; to train, improve, and refine our AI models using aggregated and anonymised data; and for any other purpose with your consent.</p>

      <h2>8. Retention of Data</h2>
      <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. Specifically: account data is retained for as long as your account is active and for 12 months thereafter; usage data is retained for up to 24 months for analytics purposes; AI interaction data used for model improvement is anonymised and aggregated within 90 days of collection; and we will retain and use your Personal Data to comply with our legal obligations, resolve disputes, and enforce our agreements.</p>

      <h2>9. Transfer of Data</h2>
      <p>Your information, including Personal Data, may be transferred to and maintained on computers located outside of your country. As we are based in the United Kingdom, data may be processed in the UK and/or transferred to countries where our service providers operate. Where we transfer Personal Data outside of the UK or the EEA, we ensure that adequate safeguards are in place, including transfers to countries with an adequacy decision, the use of Standard Contractual Clauses (SCCs), and other lawful transfer mechanisms.</p>

      <h2>10. Disclosure of Data</h2>
      <p>We may disclose personal information that we collect, or you provide: for law enforcement purposes if required by law; in connection with a business transaction such as a merger or acquisition; to contractors and service providers bound by contractual obligations to keep Personal Data confidential; to fulfil the purpose for which you provide it; for any other purpose disclosed by us when you provide the information; with your consent; and if we believe disclosure is necessary to protect the rights, property, or safety of the Company, our customers, or others.</p>

      <h2>11. Security of Data</h2>
      <p>We implement appropriate technical and organisational measures to protect your Personal Data, including encryption of data in transit using TLS/SSL, regular security assessments, access controls, and secure development practices. However, no method of transmission over the Internet or electronic storage is 100% secure, and we cannot guarantee absolute security.</p>

      <h2>12. Data Breach Notification</h2>
      <p>In the event of a personal data breach that is likely to result in a risk to the rights and freedoms of natural persons, we will notify the relevant supervisory authority within 72 hours, notify affected data subjects without undue delay where the breach is likely to result in a high risk, and document all personal data breaches.</p>

      <h2>13. Your Data Protection Rights Under UK GDPR and EU GDPR</h2>
      <p>If you are a resident of the United Kingdom, the EU, or the EEA, you have the following rights: the right of access (we will respond within one month); the right to rectification; the right to erasure; the right to restrict processing; the right to object to processing; the right to data portability; the right to withdraw consent; and rights related to automated decision-making.</p>
      <p>You have the right to complain to the UK Information Commissioner&rsquo;s Office (ICO) at <a href="https://ico.org.uk">https://ico.org.uk</a>, or your local EU/EEA data protection authority.</p>

      <h2>14. Your Rights Under the California Consumer Privacy Act (CCPA) and California Privacy Rights Act (CPRA)</h2>
      <p>If you are a California resident, you have the following rights: the right to know what Personal Data we collect; the right to delete; the right to correct; the right to opt-out of sale or sharing (we do not sell your data); the right to non-discrimination; and the right to limit use of sensitive personal information (we do not collect sensitive personal information as defined by the CCPA/CPRA). To exercise any of these rights, contact us at bevytheapp@gmail.com. We will respond within 45 days.</p>
      <p>Our Policy on &ldquo;Do Not Track&rdquo; Signals: We honour Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place.</p>

      <h2>15. Service Providers</h2>
      <p>We may employ third-party companies to facilitate our Service. Our current Service Providers include analytics providers (Google Analytics, Mixpanel), cloud hosting and infrastructure providers, and AI service providers. All Service Providers are bound by data processing agreements.</p>

      <h2>16. Analytics</h2>
      <p><strong>Google Analytics:</strong> For more information, visit <a href="https://policies.google.com/privacy?hl=en">Google Privacy Terms</a>.</p>
      <p><strong>Mixpanel:</strong> To opt out, visit <a href="https://mixpanel.com/optout/">Mixpanel Opt-out</a>. For more information, visit <a href="https://mixpanel.com/terms/">Mixpanel Terms</a>.</p>

      <h2>17. Behavioural Remarketing</h2>
      <p>Bevy may use remarketing services to advertise on third-party websites after you visit our Service. Google Ads and Facebook/Meta may be used for this purpose. You may opt out of personalised advertising through their respective settings.</p>

      <h2>18. Links to Other Sites</h2>
      <p>Our Service may contain links to other sites not operated by us. We strongly advise you to review the Privacy Policy of every site you visit. We assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>

      <h2>19. Children&rsquo;s Privacy</h2>
      <p>Our Service is not intended for use by children under the age of 18. We do not knowingly collect personally identifiable information from children under 18. If you become aware that a Child has provided us with Personal Data, please contact us immediately at bevytheapp@gmail.com.</p>

      <h2>20. AI-Specific Privacy Disclosures</h2>
      <p>Our AI systems generate truth or dare prompts. Individual user data is not used in identifiable form for training purposes. Data shared with third-party AI providers is governed by data processing agreements. The Service uses AI to automatically generate content, but this does not produce legal effects concerning you.</p>

      <h2>21. International Data Transfers</h2>
      <p>For transfers outside the UK/EEA, we rely on UK adequacy regulations, the UK International Data Transfer Agreement (IDTA) or EU Standard Contractual Clauses (SCCs), and other appropriate safeguards. You may request a copy of the safeguards by contacting us.</p>

      <h2>22. Changes to This Privacy Policy</h2>
      <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the &ldquo;Effective date&rdquo; at the top. For material changes, we will make reasonable efforts to notify you via email and/or a prominent notice on our Service.</p>

      <h2>23. Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, wish to exercise your data protection rights, or have a complaint, please contact us:</p>
      <p>By email: bevytheapp@gmail.com<br />Operator: Anant Jain<br />Location: London, United Kingdom</p>
      <p>For UK residents, you may lodge a complaint with the ICO: <a href="https://ico.org.uk/make-a-complaint/">https://ico.org.uk/make-a-complaint/</a>.</p>
    </LegalLayout>
  );
}
