import LegalLayout from "@/components/LegalLayout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - Bevy",
  description: "Privacy Policy for the Bevy mobile application.",
};

export default function PrivacyPolicy() {
  return (
    <LegalLayout title="Privacy Policy">
      <p><strong>Effective date: 04/04/2026</strong></p>

      <h2>1. Introduction</h2>
      <p>Welcome to Bevy, an AI-powered truth or dare mobile application operated by Anant Jain (&ldquo;us,&rdquo; &ldquo;we,&rdquo; or &ldquo;our&rdquo;). This Privacy Policy governs your use of Bevy (the &ldquo;Service&rdquo;) and explains how we collect, safeguard, and disclose information resulting from your use of our Service.</p>
      <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used herein have the same meanings as in our Terms of Service.</p>
      <p>Our Terms of Service (&ldquo;Terms&rdquo;) govern all use of our Service and, together with this Privacy Policy and our Legal Disclaimer, constitute your agreement with us (&ldquo;Agreement&rdquo;).</p>

      <h2>2. Data Controller</h2>
      <p>For the purposes of the UK General Data Protection Regulation (UK GDPR), the EU General Data Protection Regulation (EU GDPR), and other applicable data protection laws, the data controller is:</p>
      <p>Anant Jain<br />Email: bevytheapp@gmail.com<br />Location: London, United Kingdom</p>

      <h2>3. Definitions</h2>
      <p><strong>SERVICE:</strong> The Bevy mobile application operated by Anant Jain.</p>
      <p><strong>PERSONAL DATA:</strong> Any information relating to an identified or identifiable natural person.</p>
      <p><strong>USAGE DATA:</strong> Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</p>
      <p><strong>AI DATA:</strong> Data processed by or generated through our artificial intelligence systems, including prompt identifiers and interaction patterns.</p>
      <p><strong>DATA CONTROLLER:</strong> The natural or legal person who determines the purposes and means of processing personal data. For this Privacy Policy, Anant Jain is the Data Controller.</p>
      <p><strong>DATA PROCESSORS (OR SERVICE PROVIDERS):</strong> Any natural or legal person who processes data on behalf of the Data Controller.</p>
      <p><strong>DATA SUBJECT:</strong> Any living individual who is the subject of Personal Data.</p>
      <p><strong>USER:</strong> The individual using our Service. The User corresponds to the Data Subject.</p>

      <h2>4. Legal Basis for Processing (UK GDPR / EU GDPR)</h2>
      <p>We process your Personal Data on one or more of the following legal bases:</p>
      <ul>
        <li><strong>Consent:</strong> You have given consent to the processing of your Personal Data for one or more specific purposes.</li>
        <li><strong>Performance of a Contract:</strong> Processing is necessary for the performance of a contract to which you are a party.</li>
        <li><strong>Legitimate Interests:</strong> Processing is necessary for our legitimate interests, such as improving the Service and understanding usage patterns, except where such interests are overridden by your interests or fundamental rights and freedoms.</li>
        <li><strong>Legal Obligation:</strong> Processing is necessary for compliance with a legal obligation to which we are subject.</li>
      </ul>

      <h2>5. No User Accounts</h2>
      <p>Bevy does not require or support user accounts. There is no registration, login, or sign-up process. We do not collect your name, email address, phone number, or any other account-related personal information. All app preferences and user-created content (such as custom cards and packs) are stored locally on your device. While we do not maintain user accounts, our analytics and subscription management services generate anonymous identifiers to provide the Service. These identifiers cannot be used to identify you personally.</p>

      <h2>6. Types of Data Collected</h2>
      <h3>Usage Data (via Analytics)</h3>
      <p>We use Mixpanel, a third-party analytics service, to collect anonymous usage data. This includes: device type and model, operating system version, the features of the Service you use, interaction patterns and frequency of use, session duration, app version, and anonymous device identifiers generated by Mixpanel. We do not collect your IP address directly, though Mixpanel may process IP addresses for geolocation purposes on their servers. Mixpanel&rsquo;s automatic event tracking is disabled; we only track specific, defined events.</p>
      <h3>Onboarding Preferences</h3>
      <p>During onboarding, the app collects your gameplay preferences (such as play mode, mood, comfort level, and challenge style). These are sent to our analytics provider in anonymous, aggregated form to help us improve the Service. Your onboarding preferences are also stored locally on your device to personalise your experience.</p>
      <h3>AI Interaction Data</h3>
      <p>When you use our AI-powered features, we send only a numeric prompt identifier to our AI backend. We do not send your personal data, the text of cards, your search queries, or any user-generated content to our servers. Interaction patterns (such as frequency of AI feature usage) are tracked anonymously via analytics.</p>
      <h3>Subscription and Purchase Data</h3>
      <p>Subscription and in-app purchase transactions are processed entirely by Apple through the App Store. We use RevenueCat, a third-party subscription management service, to verify purchase status and manage entitlements. RevenueCat generates an anonymous user identifier that is cross-referenced with our analytics to understand subscription behaviour in aggregate. This anonymous identifier is included as a property on analytics events to enable aggregate analysis of subscription behaviour. We do not have access to your payment details, credit card information, or Apple ID.</p>
      <h3>Photo Library Access</h3>
      <p>With your permission, Bevy may save card images to your device&rsquo;s photo library. We do not read from or access your existing photos.</p>
      <h3>Local Notifications</h3>
      <p>With your permission, Bevy may send local notifications to remind you to play. These notifications are generated and scheduled entirely on your device and are not sent from any server. They may include promotional messages about the app.</p>
      <h3>Widget Data</h3>
      <p>If you use the Bevy home screen widget, card prompts and related display data are shared between the app and the widget extension via a local shared container on your device. No data leaves your device for this purpose.</p>
      <h3>Local Game Data</h3>
      <p>Game progress, achievements, and gameplay statistics are stored locally on your device.</p>
      <h3>Data We Do NOT Collect</h3>
      <p>We do not collect: your name, email address, or any personally identifiable contact information; special category data (racial or ethnic origin, political opinions, religious beliefs, trade union membership, genetic or biometric data, health data, or data concerning sex life or sexual orientation); financial or payment information (all payments are processed by Apple); precise geolocation data; contacts, microphone, camera, or any other device sensor data; or the text content of cards you view, create, or interact with.</p>

      <h2>7. Use of Data</h2>
      <p>We use the collected anonymous data for the following purposes: to provide and maintain our Service; to understand how the Service is used and identify areas for improvement; to detect, prevent, and address technical issues; to monitor aggregate usage patterns; and to improve the quality and relevance of AI-generated content using aggregated, anonymous data.</p>

      <h2>8. Retention of Data</h2>
      <p>Anonymous analytics data is retained for up to 24 months. AI interaction data (prompt identifiers) is not stored on our servers beyond the duration of the request. Locally stored data (preferences, custom cards, packs) remains on your device until you delete the app or clear its data. Certain security-sensitive data (such as subscription status) is stored in the iOS Keychain, which may persist across app reinstalls until manually cleared by the operating system. We will retain data as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements.</p>

      <h2>9. Transfer of Data</h2>
      <p>Your anonymous usage data may be processed by our service providers in countries outside the United Kingdom or the EEA. Where we transfer data outside of the UK or the EEA, we ensure that adequate safeguards are in place, including transfers to countries with an adequacy decision, the use of Standard Contractual Clauses (SCCs), and other lawful transfer mechanisms.</p>

      <h2>10. Disclosure of Data</h2>
      <p>We may disclose anonymous usage data: for law enforcement purposes if required by law; in connection with a business transaction such as a merger or acquisition; to our service providers bound by data processing agreements; and if we believe disclosure is necessary to protect the rights, property, or safety of the Company, our users, or others.</p>

      <h2>11. Security of Data</h2>
      <p>We implement appropriate technical and organisational measures to protect your data, including: encryption of data in transit using TLS/SSL; HMAC-signed API requests for AI service communication; secure storage of sensitive local data (subscription status, token balances) in the iOS Keychain; regular security assessments; and secure development practices. However, no method of transmission over the Internet or electronic storage is 100% secure, and we cannot guarantee absolute security.</p>

      <h2>12. Data Breach Notification</h2>
      <p>In the event of a personal data breach that is likely to result in a risk to the rights and freedoms of natural persons, we will notify the relevant supervisory authority within 72 hours, notify affected data subjects without undue delay where the breach is likely to result in a high risk, and document all personal data breaches.</p>

      <h2>13. Your Data Protection Rights Under UK GDPR and EU GDPR</h2>
      <p>If you are a resident of the United Kingdom, the EU, or the EEA, you have the following rights: the right of access; the right to rectification; the right to erasure; the right to restrict processing; the right to object to processing; the right to data portability; the right to withdraw consent; and rights related to automated decision-making. As we do not maintain user accounts, exercising these rights will primarily relate to your anonymous analytics data. Contact us at bevytheapp@gmail.com and we will assist you in identifying and processing your request.</p>
      <p>You have the right to complain to the UK Information Commissioner&rsquo;s Office (ICO) at <a href="https://ico.org.uk">https://ico.org.uk</a>, or your local EU/EEA data protection authority.</p>

      <h2>14. Your Rights Under the California Consumer Privacy Act (CCPA) and California Privacy Rights Act (CPRA)</h2>
      <p>If you are a California resident, you have the following rights: the right to know what Personal Data we collect; the right to delete; the right to correct; the right to opt-out of sale or sharing (we do not sell your data); the right to non-discrimination; and the right to limit use of sensitive personal information (we do not collect sensitive personal information as defined by the CCPA/CPRA). To exercise any of these rights, contact us at bevytheapp@gmail.com. We will respond within 45 days.</p>

      <h2>15. Service Providers</h2>
      <p>We employ the following third-party service providers:</p>
      <ul>
        <li><strong>Mixpanel</strong> &mdash; Analytics. Collects anonymous usage data to help us understand how the Service is used. To opt out, visit <a href="https://mixpanel.com/optout/">Mixpanel Opt-out</a>. For more information, visit <a href="https://mixpanel.com/terms/">Mixpanel Terms</a>.</li>
        <li><strong>RevenueCat</strong> &mdash; Subscription and purchase management. Verifies subscription status and manages in-app purchase entitlements.</li>
        <li><strong>Modal</strong> &mdash; AI infrastructure hosting. Hosts the backend that processes AI-powered features. Only numeric prompt identifiers are sent to this service; no personal data is transmitted.</li>
      </ul>
      <p>All service providers are bound by data processing agreements and are contractually obligated to keep data confidential and process it only as instructed.</p>

      <h2>16. No Advertising or Remarketing</h2>
      <p>We do not use any advertising SDKs, remarketing services, or behavioural advertising technologies. We do not serve ads within the app, and we do not share your data with advertising networks.</p>

      <h2>17. Links to Other Sites</h2>
      <p>Our Service may contain links to other sites not operated by us. We strongly advise you to review the Privacy Policy of every site you visit. We assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>

      <h2>18. Children&rsquo;s Privacy</h2>
      <p>Our Service is not intended for use by children under the age of 18. We do not knowingly collect personally identifiable information from children under 18. If you become aware that a child has provided us with Personal Data, please contact us immediately at bevytheapp@gmail.com.</p>

      <h2>19. AI-Specific Privacy Disclosures</h2>
      <p>Our AI systems generate truth or dare prompts. Only a numeric prompt identifier is sent to our AI backend; no personal data, card text, or user-generated content is transmitted. Data shared with our AI infrastructure provider is governed by a data processing agreement. The Service uses AI to automatically generate content, but this does not produce legal effects concerning you.</p>

      <h2>20. International Data Transfers</h2>
      <p>For transfers outside the UK/EEA, we rely on UK adequacy regulations, the UK International Data Transfer Agreement (IDTA) or EU Standard Contractual Clauses (SCCs), and other appropriate safeguards. You may request a copy of the safeguards by contacting us.</p>

      <h2>21. Changes to This Privacy Policy</h2>
      <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the &ldquo;Effective date&rdquo; at the top. For material changes, we will make reasonable efforts to notify you via a prominent notice on our Service.</p>

      <h2>22. Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, wish to exercise your data protection rights, or have a complaint, please contact us:</p>
      <p>By email: bevytheapp@gmail.com<br />Operator: Anant Jain<br />Location: London, United Kingdom</p>
      <p>For UK residents, you may lodge a complaint with the ICO: <a href="https://ico.org.uk/make-a-complaint/">https://ico.org.uk/make-a-complaint/</a>.</p>
    </LegalLayout>
  );
}
